version: 2.1

jobs:
  build:
    docker:
      - image: cloudreach/sceptre-circleci-sonarqube:latest

    steps:
      - checkout

      - restore_cache:
          key:
            v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile"
            }}

      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install --upgrade pip
            pip3 install -r requirements.txt

      - save_cache:
          key:
            v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile"
            }}
          paths:
            - 'venv'

      - run:
          name: Install Resolver
          command: |
            . venv/bin/activate
            pip3 install -e .

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project

  lint-and-unit-test:
    docker:
      - image: cloudreach/sceptre-circleci-sonarqube:latest

    steps:
      - attach_workspace:
          at: /home/circleci

      - checkout

      - restore_cache:
          key:
            v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile"
            }}

      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install --upgrade pip
            pip3 install -r requirements.txt

      - save_cache:
          key:
            v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile"
            }}
          paths:
            - 'venv'

      - run:
          name: Linting
          command: |
            . venv/bin/activate
            make lint

      - run:
          name: Unit Test
          command: |
            . venv/bin/activate
            mkdir test-reports
            make test

      - run:
          name: Coverage
          command: |
            . venv/bin/activate
            make coverage

      - store_test_results:
          path: test-reports
          destination: test-reports

      - store_test_results:
          path: coverage.xml
          destination: coverage-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - store_artifacts:
          path: coverage.xml
          destination: coverage-reports

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project

  sonar:
    docker:
      - image: cloudreach/sceptre-circleci-sonarqube:latest
    steps:
      - attach_workspace:
          at: /home/circleci

      - run:
          name: Run Sonarqube
          command: |
            . venv/bin/activate
            make sonar

  deploy-test:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install --upgrade pip
            pip3 install -r requirements.txt

          paths:
            - 'venv'

      - run:
          name: Initialise .pypirc
          command: |
            echo -e "[distutils]\n  index-servers =\n    test-pypi\n\n" >> ~/.pypirc
            echo -e "[test-pypi]" >> ~/.pypirc
            echo -e "username: $PYPI_TEST_USER" >> ~/.pypirc
            echo -e "password: $PYPI_TEST_PASSWORD" >> ~/.pypirc
            echo -e "repository: https://test.pypi.org/legacy/" >> ~/.pypirc

      - run:
          name: Create Distribution
          command: |
            . venv/bin/activate
            make dist

      - run:
          name: Upload to PyPi
          command: |
            . venv/bin/activate
            twine upload -r test-pypi dist/*

  deploy-production:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install --upgrade pip
            pip3 install -r requirements.txt

          paths:
            - 'venv'

      - run:
          name: init .pypirc
          command: |
            echo -e "[distutils]\n  index-servers =\n    pypi\n\n" >> ~/.pypirc
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username: $PYPI_PROD_USER" >> ~/.pypirc
            echo -e "password: $PYPI_PROD_PASSWORD" >> ~/.pypirc

      - run:
          name: Create Distribution
          command: |
            . venv/bin/activate
            make dist

      - run:
          name: Upload to PyPi
          command: |
            . venv/bin/activate
            twine upload -r pypi dist/*
workflows:
  build-test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

      - lint-and-unit-test:
          requires:
            - build
          filters:
            tags:
              only: /.*/

      - sonar:
          context: sceptre-templates-context
          requires:
            - build
            - lint-and-unit-test

      - deploy-test:
          context: sceptre-templates-context
          requires:
            - build
            - lint-and-unit-test
            - sonar
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
            branches:
              ignore: /.*/
      - hold:
          type: approval
          requires:
            - deploy-test

      - deploy-production:
          context: sceptre-templates-context
          requires:
            - build
            - lint-and-unit-test
            - sonar
            - deploy-test
            - hold
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
            branches:
              ignore: /.*/
