name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  pypi-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Publish to pypi
        run: poetry publish --build -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
